### ISSUE TITLE
src/lowlevel/node-hid.js: macOS & interface number

### ISSUE THREAD

**Issue by Quentin-M** [trezor/trezor-link#1]
https://github.com/trezor/trezor-link/commit/be1272d52726d775a320e3d56be0bbc4e8f79f52 introduces a match over the interface number == 0. However, on macOS 10.12.1, at least, the interface number is set to `-1` systematically, preventing the library from finding the TREZOR device.

```
{ vendorId: 21324,
    productId: 1,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/TREZOR@14100000/U2F Interface@1/IOUSBHostHIDDevice@14100000,1',
    serialNumber: '4A10A0367FB8A8A1089F4AEA',
    manufacturer: 'SatoshiLabs',
    product: 'TREZOR',
    release: 256,
    interface: -1,
    usagePage: 61904,
    usage: 1 },
```

**Comment by jowy** [comment]
I'm running in to this as well.

**Comment by jcsmesquita** [comment]
Same here... I was trying to connect to the trezor through node-hid on my Mac (electron app) and it's dead... I can get a connection with trezord running but can we get node-hid working again?

**Comment by karel-3d** [comment]
Removed node-hid altogether now, it was too hard to maintain
