### ISSUE TITLE
Remove bridge1 artefacts 

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-link#13]
https://github.com/trezor/trezor-link/blob/master/src/bridge/v1.js should not be used anywhere anymore.

**Comment by prusnak** [comment]
Also README.md should not use `config_signed.bin`

**Comment by alexbarnsley** [comment]
@prusnak how would i go about using `trezor-link` without `config_signed.bin`? I'm struggling to find out how to generate the file, so would be good to know the alternative method. Thanks

**Comment by prusnak** [comment]
If you use the current bridge you should not need the signed config. This is used only for bridge v1 and trezor chrome extension.

**Comment by tsusanka** [comment]
Already done.
