### ISSUE TITLE
Unhandled WebUsb Error: LowLevelTransportWithSharedConnections.call Error: Device released or disconnected

### ISSUE THREAD

**Issue by keip** [trezor/trezor-link#17]
Model T WebUSB (no-bridge): When you have an confirm on device and you call getFeatures() to cancel the confirm this error will follow:

<img width="1316" alt="tinygrab screen shot 17-01-2019 12 13 23" src="https://user-images.githubusercontent.com/1011630/51317223-4db9a600-1a57-11e9-8616-2737382d9099.png">

**Comment by szymonlesisz** [comment]
This issue, does not belong here. 
It's a [trezor-connect](https://github.com/trezor/connect) issue. 
tbh it's just an unhandled error and it doesn't break anything.
Connect sometimes call "release session" on device which was already released before, just to make sure it's really released.

As i can tell from your log you did receive your response.
