### ISSUE TITLE
Expose error messages

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-link#4]
We need to export error messages up, to avoid string comparison.
Example:

trezor-link will throw Error("device not found"); to catch it and react properly i need to compare error.message with local string "device not found".

Better solution is:

export const DEVICE_NOT_FOUND = new Error('device not found');

then:

import { DEVICE_NOT_FOUND } from 'trezor-link';

and then:

if (error === DEVICE_NOT_FOUND) { ... }

**Comment by tsusanka** [comment]
Moved to #4601.
