### ISSUE TITLE
lowlevel/webusb unreadableHidDevice should be emited as response of enumerate

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-link#40]
problems:
- incremental device path is missing (there could be two unreadable devices)
- error handling needs to be implemented differently on user side (example in [connect](https://github.com/trezor/connect/blob/83c20ddc70092e8ca23af59abc8810035676f062/src/js/device/DeviceList.js#L182))

solution:
process hid devices is the same way as `bootloader` devices
https://github.com/trezor/trezor-link/blob/master/src/lowlevel/webusb.js#L86

process `unreadableHidDeviceChange` internally and resolve it by `enumerate` response

**Comment by tsusanka** [comment]
Moved to #4601.
