### ISSUE TITLE
Request to Bridge v2 fails with 403

### ISSUE THREAD

**Issue by wbobeirne** [trezor/trezor-link#7]
I'm trying to use `trezor.js` with Bridge v2 installed, but it won't find my device. After some digging, it looks like the [request to 127.0.0.1:21325](https://github.com/trezor/trezor-link/blob/master/src/bridge/v2.js#L62) fails with a 403 despite me being able to load it in the browser. It's coming back with a 403 code, so I think it may be CORS related. Am I doing something incorrectly, or is the way I'm going about integrating Trezor into a node application incorrect? Here's my code:

```.ts
import { DeviceList } from 'trezor.js';
const deviceList = new DeviceList({ debug: false });
// ...
const { session } = await deviceList.acquireFirstDevice(true);
```

**Comment by prusnak** [comment]
You cannot access the bridge from the browser unless the request comes
from *.trezor.io domain.
I suggest you study trezor/connect to learn how to integrate with your
web application.

**Comment by wbobeirne** [comment]
I'm trying to access it via node (In an Electron app, but on the node side, not the browser renderer) so connect won't work for me. Looking at [this thread](https://github.com/trezor/trezor.js/issues/37) leads me to believe that this use case was initially supported by `node-hid`, but has since been removed. Does that mean accessing the device via node is no longer possible?

**Comment by wbobeirne** [comment]
It also looks like the use-case of connecting in node via Bridge v1/v2 was considered, at least at some point (See here: https://github.com/trezor/trezor-link/blob/master/src/index.js#L17 and here: https://github.com/trezor/trezor.js/blob/master/src/index-node.js#L18)

**Comment by wbobeirne** [comment]
Alright, I tracked it down to `trezord-go`, looks like it at some point was supposed to allow origin-less requests, but that's been commented out: https://github.com/trezor/trezord-go/blob/2b2bcd295d93f4c130c16e7ce3d173bceb5fe1e5/server/api/api.go#L219. I'm going to open an issue over there.

I've opened an issue on `trezord-go` since I think that's where the fix would have to happen: https://github.com/trezor/trezord-go/issues/68

**Comment by karel-3d** [comment]
This was fixed by url spoofing in trezor.js, is that good? Closing this
